CREATE TABLE `users`(
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`username` VARCHAR(100) NOT NULL UNIQUE,
	`password` VARCHAR(100) NOT NULL,
	`email` VARCHAR(100) NOT NULL,
)ENGINE = InnoDB;
